//! TUI color customization: [`ThemeColorOverrides`] and [`ColorLabel`].

use serde::{Deserialize, Serialize};

/// Optional color overrides for TUI theme elements, specified as CSS-style hex strings.
#[derive(Debug, Default, Clone, Serialize, Deserialize)]
pub struct ThemeColorOverrides {
    pub user_character_fg: Option<String>,
    pub user_character_bg: Option<String>,
    pub side_character_fg: Option<String>,
    pub side_character_bg: Option<String>,
    pub file_reference_fg: Option<String>,
    pub assistant_message_fg: Option<String>,
    pub assistant_message_bg: Option<String>,
    pub system_message: Option<String>,
    pub border_focused: Option<String>,
    pub border_unfocused: Option<String>,
    pub status_bar_fg: Option<String>,
    pub status_bar_bg: Option<String>,
    pub status_error_fg: Option<String>,
    pub status_error_bg: Option<String>,
    pub status_info_fg: Option<String>,
    pub status_info_bg: Option<String>,
    pub status_warning_fg: Option<String>,
    pub status_warning_bg: Option<String>,
    pub dialogue: Option<String>,
    pub nav_cursor_fg: Option<String>,
    pub nav_cursor_bg: Option<String>,
    pub hover_bg: Option<String>,
    pub dimmed: Option<String>,
    pub sidebar_highlight_fg: Option<String>,
    pub sidebar_highlight_bg: Option<String>,
    pub command_picker_fg: Option<String>,
    pub command_picker_bg: Option<String>,
    pub streaming_indicator: Option<String>,
    pub api_unavailable: Option<String>,
    pub summary_indicator: Option<String>,
    pub token_band_ok: Option<String>,
    pub token_band_warn: Option<String>,
    pub token_band_over: Option<String>,
    pub group_character_fg_1: Option<String>,
    pub group_character_fg_2: Option<String>,
    pub group_character_fg_3: Option<String>,
    pub group_character_fg_4: Option<String>,
    pub group_character_fg_5: Option<String>,
    pub group_character_fg_6: Option<String>,
    pub group_character_fg_7: Option<String>,
    pub group_character_fg_8: Option<String>,
    pub group_character_bg_1: Option<String>,
    pub group_character_bg_2: Option<String>,
    pub group_character_bg_3: Option<String>,
    pub group_character_bg_4: Option<String>,
    pub group_character_bg_5: Option<String>,
    pub group_character_bg_6: Option<String>,
    pub group_character_bg_7: Option<String>,
    pub group_character_bg_8: Option<String>,
    pub missing_character_badge_fg: Option<String>,
    pub search_highlight_fg: Option<String>,
    pub search_highlight_bg: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ColorLabel {
    UserCharacterFg,
    UserCharacterBg,
    SideCharacterFg,
    SideCharacterBg,
    FileReferenceFg,
    AssistantMessageFg,
    AssistantMessageBg,
    SystemMessage,
    Dialogue,
    BorderFocused,
    BorderUnfocused,
    StatusBarFg,
    StatusBarBg,
    StatusErrorFg,
    StatusErrorBg,
    StatusInfoFg,
    StatusInfoBg,
    StatusWarningFg,
    StatusWarningBg,
    NavCursorFg,
    NavCursorBg,
    HoverBg,
    SidebarHighlightFg,
    SidebarHighlightBg,
    Dimmed,
    CommandPickerFg,
    CommandPickerBg,
    StreamingIndicator,
    ApiUnavailable,
    SummaryIndicator,
    TokenBandOk,
    TokenBandWarn,
    TokenBandOver,
    GroupCharacterFg1,
    GroupCharacterFg2,
    GroupCharacterFg3,
    GroupCharacterFg4,
    GroupCharacterFg5,
    GroupCharacterFg6,
    GroupCharacterFg7,
    GroupCharacterFg8,
    GroupCharacterBg1,
    GroupCharacterBg2,
    GroupCharacterBg3,
    GroupCharacterBg4,
    GroupCharacterBg5,
    GroupCharacterBg6,
    GroupCharacterBg7,
    GroupCharacterBg8,
    MissingCharacterBadgeFg,
    SearchHighlightFg,
    SearchHighlightBg,
}

impl ColorLabel {
    pub const ALL: [ColorLabel; 52] = [
        Self::UserCharacterFg,
        Self::UserCharacterBg,
        Self::SideCharacterFg,
        Self::SideCharacterBg,
        Self::FileReferenceFg,
        Self::AssistantMessageFg,
        Self::AssistantMessageBg,
        Self::SystemMessage,
        Self::Dialogue,
        Self::BorderFocused,
        Self::BorderUnfocused,
        Self::StatusBarFg,
        Self::StatusBarBg,
        Self::StatusErrorFg,
        Self::StatusErrorBg,
        Self::StatusInfoFg,
        Self::StatusInfoBg,
        Self::StatusWarningFg,
        Self::StatusWarningBg,
        Self::NavCursorFg,
        Self::NavCursorBg,
        Self::HoverBg,
        Self::SidebarHighlightFg,
        Self::SidebarHighlightBg,
        Self::Dimmed,
        Self::CommandPickerFg,
        Self::CommandPickerBg,
        Self::StreamingIndicator,
        Self::ApiUnavailable,
        Self::SummaryIndicator,
        Self::TokenBandOk,
        Self::TokenBandWarn,
        Self::TokenBandOver,
        Self::GroupCharacterFg1,
        Self::GroupCharacterFg2,
        Self::GroupCharacterFg3,
        Self::GroupCharacterFg4,
        Self::GroupCharacterFg5,
        Self::GroupCharacterFg6,
        Self::GroupCharacterFg7,
        Self::GroupCharacterFg8,
        Self::GroupCharacterBg1,
        Self::GroupCharacterBg2,
        Self::GroupCharacterBg3,
        Self::GroupCharacterBg4,
        Self::GroupCharacterBg5,
        Self::GroupCharacterBg6,
        Self::GroupCharacterBg7,
        Self::GroupCharacterBg8,
        Self::MissingCharacterBadgeFg,
        Self::SearchHighlightFg,
        Self::SearchHighlightBg,
    ];

    pub const fn name(self) -> &'static str {
        match self {
            Self::UserCharacterFg => "user_character_fg",
            Self::UserCharacterBg => "user_character_bg",
            Self::SideCharacterFg => "side_character_fg",
            Self::SideCharacterBg => "side_character_bg",
            Self::FileReferenceFg => "file_reference_fg",
            Self::AssistantMessageFg => "assistant_message_fg",
            Self::AssistantMessageBg => "assistant_message_bg",
            Self::SystemMessage => "system_message",
            Self::Dialogue => "dialogue",
            Self::BorderFocused => "border_focused",
            Self::BorderUnfocused => "border_unfocused",
            Self::StatusBarFg => "status_bar_fg",
            Self::StatusBarBg => "status_bar_bg",
            Self::StatusErrorFg => "status_error_fg",
            Self::StatusErrorBg => "status_error_bg",
            Self::StatusInfoFg => "status_info_fg",
            Self::StatusInfoBg => "status_info_bg",
            Self::StatusWarningFg => "status_warning_fg",
            Self::StatusWarningBg => "status_warning_bg",
            Self::NavCursorFg => "nav_cursor_fg",
            Self::NavCursorBg => "nav_cursor_bg",
            Self::HoverBg => "hover_bg",
            Self::SidebarHighlightFg => "sidebar_highlight_fg",
            Self::SidebarHighlightBg => "sidebar_highlight_bg",
            Self::Dimmed => "dimmed",
            Self::CommandPickerFg => "command_picker_fg",
            Self::CommandPickerBg => "command_picker_bg",
            Self::StreamingIndicator => "streaming_indicator",
            Self::ApiUnavailable => "api_unavailable",
            Self::SummaryIndicator => "summary_indicator",
            Self::TokenBandOk => "token_band_ok",
            Self::TokenBandWarn => "token_band_warn",
            Self::TokenBandOver => "token_band_over",
            Self::GroupCharacterFg1 => "group_character_fg_1",
            Self::GroupCharacterFg2 => "group_character_fg_2",
            Self::GroupCharacterFg3 => "group_character_fg_3",
            Self::GroupCharacterFg4 => "group_character_fg_4",
            Self::GroupCharacterFg5 => "group_character_fg_5",
            Self::GroupCharacterFg6 => "group_character_fg_6",
            Self::GroupCharacterFg7 => "group_character_fg_7",
            Self::GroupCharacterFg8 => "group_character_fg_8",
            Self::GroupCharacterBg1 => "group_character_bg_1",
            Self::GroupCharacterBg2 => "group_character_bg_2",
            Self::GroupCharacterBg3 => "group_character_bg_3",
            Self::GroupCharacterBg4 => "group_character_bg_4",
            Self::GroupCharacterBg5 => "group_character_bg_5",
            Self::GroupCharacterBg6 => "group_character_bg_6",
            Self::GroupCharacterBg7 => "group_character_bg_7",
            Self::GroupCharacterBg8 => "group_character_bg_8",
            Self::MissingCharacterBadgeFg => "missing_character_badge_fg",
            Self::SearchHighlightFg => "search_highlight_fg",
            Self::SearchHighlightBg => "search_highlight_bg",
        }
    }

    pub fn from_name(label: &str) -> Option<Self> {
        Self::ALL.iter().copied().find(|l| l.name() == label)
    }
}

impl ThemeColorOverrides {
    pub fn get(&self, label: ColorLabel) -> Option<&str> {
        let slot = match label {
            ColorLabel::UserCharacterFg => &self.user_character_fg,
            ColorLabel::UserCharacterBg => &self.user_character_bg,
            ColorLabel::SideCharacterFg => &self.side_character_fg,
            ColorLabel::SideCharacterBg => &self.side_character_bg,
            ColorLabel::FileReferenceFg => &self.file_reference_fg,
            ColorLabel::AssistantMessageFg => &self.assistant_message_fg,
            ColorLabel::AssistantMessageBg => &self.assistant_message_bg,
            ColorLabel::SystemMessage => &self.system_message,
            ColorLabel::Dialogue => &self.dialogue,
            ColorLabel::BorderFocused => &self.border_focused,
            ColorLabel::BorderUnfocused => &self.border_unfocused,
            ColorLabel::StatusBarFg => &self.status_bar_fg,
            ColorLabel::StatusBarBg => &self.status_bar_bg,
            ColorLabel::StatusErrorFg => &self.status_error_fg,
            ColorLabel::StatusErrorBg => &self.status_error_bg,
            ColorLabel::StatusInfoFg => &self.status_info_fg,
            ColorLabel::StatusInfoBg => &self.status_info_bg,
            ColorLabel::StatusWarningFg => &self.status_warning_fg,
            ColorLabel::StatusWarningBg => &self.status_warning_bg,
            ColorLabel::NavCursorFg => &self.nav_cursor_fg,
            ColorLabel::NavCursorBg => &self.nav_cursor_bg,
            ColorLabel::HoverBg => &self.hover_bg,
            ColorLabel::SidebarHighlightFg => &self.sidebar_highlight_fg,
            ColorLabel::SidebarHighlightBg => &self.sidebar_highlight_bg,
            ColorLabel::Dimmed => &self.dimmed,
            ColorLabel::CommandPickerFg => &self.command_picker_fg,
            ColorLabel::CommandPickerBg => &self.command_picker_bg,
            ColorLabel::StreamingIndicator => &self.streaming_indicator,
            ColorLabel::ApiUnavailable => &self.api_unavailable,
            ColorLabel::SummaryIndicator => &self.summary_indicator,
            ColorLabel::TokenBandOk => &self.token_band_ok,
            ColorLabel::TokenBandWarn => &self.token_band_warn,
            ColorLabel::TokenBandOver => &self.token_band_over,
            ColorLabel::GroupCharacterFg1 => &self.group_character_fg_1,
            ColorLabel::GroupCharacterFg2 => &self.group_character_fg_2,
            ColorLabel::GroupCharacterFg3 => &self.group_character_fg_3,
            ColorLabel::GroupCharacterFg4 => &self.group_character_fg_4,
            ColorLabel::GroupCharacterFg5 => &self.group_character_fg_5,
            ColorLabel::GroupCharacterFg6 => &self.group_character_fg_6,
            ColorLabel::GroupCharacterFg7 => &self.group_character_fg_7,
            ColorLabel::GroupCharacterFg8 => &self.group_character_fg_8,
            ColorLabel::GroupCharacterBg1 => &self.group_character_bg_1,
            ColorLabel::GroupCharacterBg2 => &self.group_character_bg_2,
            ColorLabel::GroupCharacterBg3 => &self.group_character_bg_3,
            ColorLabel::GroupCharacterBg4 => &self.group_character_bg_4,
            ColorLabel::GroupCharacterBg5 => &self.group_character_bg_5,
            ColorLabel::GroupCharacterBg6 => &self.group_character_bg_6,
            ColorLabel::GroupCharacterBg7 => &self.group_character_bg_7,
            ColorLabel::GroupCharacterBg8 => &self.group_character_bg_8,
            ColorLabel::MissingCharacterBadgeFg => &self.missing_character_badge_fg,
            ColorLabel::SearchHighlightFg => &self.search_highlight_fg,
            ColorLabel::SearchHighlightBg => &self.search_highlight_bg,
        };
        slot.as_deref()
    }

    pub fn set(&mut self, label: ColorLabel, value: Option<String>) {
        let slot = match label {
            ColorLabel::UserCharacterFg => &mut self.user_character_fg,
            ColorLabel::UserCharacterBg => &mut self.user_character_bg,
            ColorLabel::SideCharacterFg => &mut self.side_character_fg,
            ColorLabel::SideCharacterBg => &mut self.side_character_bg,
            ColorLabel::FileReferenceFg => &mut self.file_reference_fg,
            ColorLabel::AssistantMessageFg => &mut self.assistant_message_fg,
            ColorLabel::AssistantMessageBg => &mut self.assistant_message_bg,
            ColorLabel::SystemMessage => &mut self.system_message,
            ColorLabel::Dialogue => &mut self.dialogue,
            ColorLabel::BorderFocused => &mut self.border_focused,
            ColorLabel::BorderUnfocused => &mut self.border_unfocused,
            ColorLabel::StatusBarFg => &mut self.status_bar_fg,
            ColorLabel::StatusBarBg => &mut self.status_bar_bg,
            ColorLabel::StatusErrorFg => &mut self.status_error_fg,
            ColorLabel::StatusErrorBg => &mut self.status_error_bg,
            ColorLabel::StatusInfoFg => &mut self.status_info_fg,
            ColorLabel::StatusInfoBg => &mut self.status_info_bg,
            ColorLabel::StatusWarningFg => &mut self.status_warning_fg,
            ColorLabel::StatusWarningBg => &mut self.status_warning_bg,
            ColorLabel::NavCursorFg => &mut self.nav_cursor_fg,
            ColorLabel::NavCursorBg => &mut self.nav_cursor_bg,
            ColorLabel::HoverBg => &mut self.hover_bg,
            ColorLabel::SidebarHighlightFg => &mut self.sidebar_highlight_fg,
            ColorLabel::SidebarHighlightBg => &mut self.sidebar_highlight_bg,
            ColorLabel::Dimmed => &mut self.dimmed,
            ColorLabel::CommandPickerFg => &mut self.command_picker_fg,
            ColorLabel::CommandPickerBg => &mut self.command_picker_bg,
            ColorLabel::StreamingIndicator => &mut self.streaming_indicator,
            ColorLabel::ApiUnavailable => &mut self.api_unavailable,
            ColorLabel::SummaryIndicator => &mut self.summary_indicator,
            ColorLabel::TokenBandOk => &mut self.token_band_ok,
            ColorLabel::TokenBandWarn => &mut self.token_band_warn,
            ColorLabel::TokenBandOver => &mut self.token_band_over,
            ColorLabel::GroupCharacterFg1 => &mut self.group_character_fg_1,
            ColorLabel::GroupCharacterFg2 => &mut self.group_character_fg_2,
            ColorLabel::GroupCharacterFg3 => &mut self.group_character_fg_3,
            ColorLabel::GroupCharacterFg4 => &mut self.group_character_fg_4,
            ColorLabel::GroupCharacterFg5 => &mut self.group_character_fg_5,
            ColorLabel::GroupCharacterFg6 => &mut self.group_character_fg_6,
            ColorLabel::GroupCharacterFg7 => &mut self.group_character_fg_7,
            ColorLabel::GroupCharacterFg8 => &mut self.group_character_fg_8,
            ColorLabel::GroupCharacterBg1 => &mut self.group_character_bg_1,
            ColorLabel::GroupCharacterBg2 => &mut self.group_character_bg_2,
            ColorLabel::GroupCharacterBg3 => &mut self.group_character_bg_3,
            ColorLabel::GroupCharacterBg4 => &mut self.group_character_bg_4,
            ColorLabel::GroupCharacterBg5 => &mut self.group_character_bg_5,
            ColorLabel::GroupCharacterBg6 => &mut self.group_character_bg_6,
            ColorLabel::GroupCharacterBg7 => &mut self.group_character_bg_7,
            ColorLabel::GroupCharacterBg8 => &mut self.group_character_bg_8,
            ColorLabel::MissingCharacterBadgeFg => &mut self.missing_character_badge_fg,
            ColorLabel::SearchHighlightFg => &mut self.search_highlight_fg,
            ColorLabel::SearchHighlightBg => &mut self.search_highlight_bg,
        };
        *slot = value;
    }

    pub fn any_set(&self) -> bool {
        ColorLabel::ALL.iter().any(|l| self.get(*l).is_some())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn file_reference_fg_in_color_label_all() {
        assert!(ColorLabel::ALL.contains(&ColorLabel::FileReferenceFg));
        assert_eq!(ColorLabel::FileReferenceFg.name(), "file_reference_fg");
        assert_eq!(
            ColorLabel::from_name("file_reference_fg"),
            Some(ColorLabel::FileReferenceFg),
        );
    }

    #[test]
    fn theme_color_overrides_file_reference_fg_round_trip() {
        let mut overrides = ThemeColorOverrides::default();
        overrides.set(ColorLabel::FileReferenceFg, Some("blue".to_owned()));
        assert_eq!(overrides.get(ColorLabel::FileReferenceFg), Some("blue"));
    }
}
