[package]
name = "libllm"
version.workspace = true
edition.workspace = true

[dependencies]
libllm-config = { workspace = true }
libllm-core = { workspace = true }
libllm-protocol = { workspace = true }
libllm-storage = { workspace = true }

[features]
test-support = ["libllm-core/test-support", "libllm-config/test-support"]

[lints]
workspace = true
